### ISSUE TITLE
The user is billed again when he resubscribes after canceling a subscription

### ISSUE THREAD

**Issue by madalincm** [mozilla/subhub#305] opened 2019-10-10 08:44 UTC
#### Affected versions:
- Firefox Release 69.0.1
- Firefox Beta 70.0b9
- Firefox Nightly 71.0a1

#### Affected Platforms:
- Windows 10 (64-bit)
- MacOS 10.14.5
- Linux Ubuntu 16.04 (64-bit)

#### Precondition
User is logged in in the Guardian VPN homepage and he does have an active subscription.
https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn

#### Steps to reproduce
1. Navigate to subscription page and cancel subscription for Firefox Guardian
2. From the same page Resubscribe to Firefox Guardian

#### Expected result:
The user is not billed again so no Payment Received email is sent to the user. 

#### Actual result:
When the user resubscribes a payment received email is sent
![userBilledAgainAfterResubscribe](https://user-images.githubusercontent.com/15685441/66553118-35dd0180-eb53-11e9-9a22-228a57ba9b51.gif)

**Comment by stlhood** [comment] 2019-10-10 16:39
Being tracked in JIRA as COPS-778.

**Comment by jackiemunroe** [comment] 2019-10-10 20:39
Update: The customer is not billed again, but receives an email indicating a purchase/charge upon subscription being updated

**Comment by madalincm** [comment] 2019-10-22 11:42
> Update: The customer is not billed again, but receives an email indicating a purchase/charge upon subscription being updated
That is correct, I have checked the stripe dashboard and the user is not billed again.
We still consider this as must fix for the release as the user will receive false information regarding how he is billed so I'm adding the major label.

**Comment by jackiemunroe** [comment] 2019-10-22 15:11
This issue is currently blocked by designs for a resubscription email.
JIRA issue tracking implementation: COPS-786

**Comment by stlhood** [comment] 2019-10-22 16:14
Content for the resubscription email is linked in COPS-786. The design should follow our standard email template.

**Comment by stlhood** [comment] 2019-10-30 19:54
Removed "Major" tag because the customer is not actually billed twice.

This issue will be resolved in the current sprint, via COPS-786.

**Comment by stlhood** [comment] 2019-11-06 04:19
COPS-786 is complete and closed. The user now receives an email that explains that they have not been charged again.

**Closed** 2019-11-06 15:05 UTC

**Comment by SoftVision-LorandJanos** [comment] 2019-11-11 08:00
This issue is no longer reproducible, using the latest Firefox Release (70.0.1). Verified on Windows 10 x64.
