### ISSUE TITLE
Download email, new subscription and payment receipt emails are not sent after the user completes the subscription process

### ISSUE THREAD

**Issue by madalincm** [mozilla/subhub#304] opened 2019-10-09 14:24 UTC
#### Affected versions:
- Firefox Release 69.0.1
- Firefox Beta 70.0b9
- Firefox Nightly 71.0a1

#### Affected Platforms:
- Windows 10 (64-bit)
- MacOS 10.14.5
- Linux Ubuntu 16.04 (64-bit)

#### Precondition
User is logged in in the Guardian VPN homepage and he does not have an active subscription.
https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn

#### Steps to reproduce
1. Click on the "Subscribe for just $9.99/mo" blue button
2. Enter valid valid info and complete the subscription process

#### Expected result:
- The Download email is sent to the user
- The New subscription email is sent to the user
- The Payment receipt email is sent to the user

#### Actual result:
- None of the above 3 emails are sent to the user

**Comment by marty331** [comment] 2019-10-09 18:44
@johngruen I'm not sure I agree with this coming to subhub, as the emails for subscription and receipt are working (for me anyway and it sounds like for madalincm) and the download email should come from FxA.

**Comment by stlhood** [comment] 2019-10-09 18:49
@madalincm is saying that subscription emails are not reliably arriving

**Comment by johngruen** [comment] 2019-10-09 18:52
@marty331 the download email is being tracked on our end per my comment above...

This appears to be an intermittent failure on the subscription email (i have not been able to repro this either)

Note, I just used the `Major` label b/c that's how this was originally filed. Feel free to triage this as you see fit.

**Comment by desiree-mofo** [comment] 2019-10-09 19:15
I verified and the record isn't making it into Salesforce for the subscription, therefore the record isn't triggered the email automation. I am working to determine if it failed to be inserted into Salesforce via Basket (working with pmac on that) and why, but no obvious errors were found as of now on the Basket side

**Comment by stlhood** [comment] 2019-10-10 16:39
Being tracked in JIRA via COPS-779.

**Comment by jackiemunroe** [comment] 2019-10-10 19:17
@stlhood @marty331 @madalincm 
I have confirmed in the logs that the trigger for the emails has been firing properly and we have been receiving a 200-OK status from Basket. After speaking with the Basket team, it appears as though yesterday they were experiencing memory issues that were causing loss of records. That team is working to resolve the issue, and there are no further steps for us to take.

Please confirm that this issue can be closed.

**Comment by SoftVision-LorandJanos** [comment] 2019-10-11 12:09
This issue is still reproducible.
I've rechecked on [Guardian VPN - Stage](https://stage.guardian.nonprod.cloudops.mozgcp.net/vpn) page, using the steps above for a few times, and had the following results:
- The "New Subscription" email is received by the user about 2 times out of 3 times.
- The "Download" email is not sent at all.

- The "Subscription cancellation" email is sent every time.

Verified on Windows 10 x64, MacOS 10.14.5, Linux Ubuntu 16.04, using Firefox Release 69.0.2.

**Comment by stlhood** [comment] 2019-10-11 15:42
@SoftVision-LorandJanos Can you provide the email address of the FxA user whose "New Subscription" email did not arrive?

@johngruen @clouserw Do we know when the fix for the download email will be live?

**Comment by jackiemunroe** [comment] 2019-10-22 15:05
@johngruen Is the download email issue still being tracked on the FxA team's end? If so, then I'd like to close out this ticket, since the Subscription email portion of this issue has been resolved.

**Comment by bbangert** [comment] 2019-10-23 01:06
@marty331 we could change the download link in stage if desired. We should file a separate issue to do so.

**Comment by johngruen** [comment] 2019-10-23 10:12
Agree with ben, we should close this issue and file a new one if we wish to update the staging email.

**Closed** 2019-10-23 14:50 UTC
Labels: [QA]:Major issue

**Comment by SoftVision-LorandJanos** [comment] 2019-11-11 15:07
This issue is no longer reproducible on [FPN-stage](https://stage.guardian.nonprod.cloudops.mozgcp.net/) site, using the latest Firefox Release (70.0.1). Verified on Windows 10 x64.
